name: Bot

on:
  issue_comment:
    types: [created, deleted]

jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dagger/dagger-for-github@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          version: "0.9.10"
          verb: call
          module: ./bot
          args: |
            handle \
            --github-token env:GITHUB_TOKEN \
            --event-name ${{ github.event_name }} \
            --event-file ${{ github.event_path }} \
